version: "2"
run:
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - gosmopolitan
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - whitespace
    - zerologlint
  disable:
    - spancheck
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gosec:
      excludes:
        - G115
      confidence: medium
    govet:
      enable:
        - shadow
    nolintlint:
      require-explanation: true
      require-specific: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    varnamelen:
      min-name-length: 2
  exclusions:
    generated: lax
    rules:
      - linters:
          - copyloopvar
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - maintidx
          - unparam
          - varnamelen
        path: _test(ing)?\.go
      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G104:'
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
    paths:
      - zz_generated\..+\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/linode/linode-blockstorage-csi-driver)
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/linode/linode-blockstorage-csi-driver
  exclusions:
    generated: lax
    paths:
      - zz_generated\..+\.go$
      - third_party$
      - builtin$
      - examples$
