FROM golang:1.23.6-alpine AS builder
# from makefile
ARG REV
ARG GOLANGCI_LINT_VERSION

RUN mkdir -p /linode
WORKDIR /linode

RUN apk add \
    blkid \
    cryptsetup \
    cryptsetup-libs \
    cryptsetup-dev \
    curl \
    e2fsprogs \
    findmnt \
    gcc \
    lsblk \
    make \
    musl-dev \
    pkgconfig \
    xfsprogs

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN CGO_ENABLED=1 go build -a -ldflags '-X main.vendorVersion='${REV}'' -o /bin/linode-blockstorage-csi-driver /linode
RUN CGO_ENABLED=1 go install go.uber.org/mock/mockgen@latest
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

CMD ["sh"]
