apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: kube-system
  labels:
    app: otel-collector
spec:
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
  selector:
    app: otel-collector
