apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: csi-linode-controller
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
  labels:
    app: csi-linode-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-linode-controller
  serviceName: csi-linode
  template:
    metadata:
      labels:
        app: csi-linode-controller
        role: csi-linode
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - args:
            - --default-fstype=ext4
            - --volume-name-prefix=pvc
            - --volume-name-uuid-length=16
            - --csi-address=$(ADDRESS)
            - --feature-gates=Topology=true
            - --v=2
            {{- if .Values.enableMetrics}}
            - --metrics-address={{ .Values.csiProvisioner.metrics.address }}
            {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          image: {{ .Values.csiProvisioner.image }}:{{ .Values.csiProvisioner.tag }}
          imagePullPolicy: {{ .Values.csiProvisioner.pullPolicy }}
          name: csi-provisioner
          {{- if .Values.enableMetrics}}
          ports:
            - name: metrics
              containerPort: {{ .Values.csiProvisioner.metrics.port }}
              protocol: TCP
          {{- end}}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - args:
            - --v=2
            - --csi-address=$(ADDRESS)
            - --timeout=30s
            {{- if .Values.enableMetrics}}
            - --metrics-address={{ .Values.csiAttacher.metrics.address }}
            {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          image: {{ .Values.csiAttacher.image }}:{{ .Values.csiAttacher.tag }}
          imagePullPolicy: {{ .Values.csiAttacher.pullPolicy }}
          name: csi-attacher
          {{- if .Values.enableMetrics}}
          ports:
            - name: metrics
              containerPort: {{ .Values.csiAttacher.metrics.port }}
              protocol: TCP
          {{- end}}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - args:
            - --v=2
            - --csi-address=$(ADDRESS)
            {{- if .Values.enableMetrics}}
            - --metrics-address={{ .Values.csiResizer.metrics.address }}
            {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          image: {{ .Values.csiResizer.image }}:{{ .Values.csiResizer.tag }}
          imagePullPolicy: {{ .Values.csiResizer.pullPolicy }}
          name: csi-resizer
          {{- if .Values.enableMetrics}}
          ports:
            - name: metrics
              containerPort: {{ .Values.csiResizer.metrics.port }}
              protocol: TCP
          {{- end}}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - args:
            - --v=2
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: LINODE_URL
              value: https://api.linode.com
            - name: DRIVER_ROLE
              value: controller
            - name: LINODE_VOLUME_LABEL_PREFIX
              value: {{ .Values.volumeLabelPrefix | default "" | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: LINODE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.secretRef }}{{ .Values.secretRef.name | default "linode" }}{{ else }}"linode"{{ end }}
                  key: {{ if .Values.secretRef }}{{ .Values.secretRef.apiTokenRef | default "token" }}{{ else }}"token"{{ end }}
            - name: ENABLE_METRICS
              value: {{ .Values.enableMetrics | quote}}
            - name: METRICS_PORT
              value: {{ .Values.metricsPort | quote}}
            - name: OTEL_TRACING
              value: {{.Values.enableTracing | quote}}
            - name: OTEL_TRACING_PORT
              value: {{.Values.tracingPort | quote}}
            {{- with .Values.csiLinodePlugin.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ .Values.csiLinodePlugin.image }}:{{ .Values.csiLinodePlugin.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.csiLinodePlugin.pullPolicy }}
          name: csi-linode-plugin
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
            {{- with .Values.csiLinodePlugin.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.csiLinodePlugin.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      serviceAccount: csi-controller-sa
      {{- if .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.controller.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.affinity }}
      affinity:
        {{- toYaml .Values.controller.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      {{- end }}
      volumes:
        - emptyDir: {}
          name: socket-dir
        - configMap:
            defaultMode: 493
            name: get-linode-id
          name: get-linode-id
        - hostPath:
            path: /dev
            type: Directory
          name: dev
        {{- with .Values.csiLinodePlugin.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
