{{- if .Values.controller.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-sa
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
{{- end }}
