{{- if .Values.daemonSet.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "csi-node-sa" .Values.daemonSet.serviceAccount.name }}
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
{{- end }}
