{{- if .Values.controller.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-controller-attacher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-attacher-role
subjects:
- kind: ServiceAccount
  name: csi-controller-sa
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
{{- end }}

