{{- if .Values.daemonSet.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node-sa
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
{{- end }}
