apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-linode-node
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
  labels:
    app: csi-linode-node
spec:
  selector:
    matchLabels:
      app: csi-linode-node
  template:
    metadata:
      labels:
        app: csi-linode-node
        role: csi-linode
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - args:
        - --v=2
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: {{ .Values.kubeletPath | default "/var/lib/kubelet" }}/plugins/linodebs.csi.linode.com/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- with .Values.csiNodeDriverRegistrar.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.csiNodeDriverRegistrar.image}}:{{ .Values.csiNodeDriverRegistrar.tag}}
        name: csi-node-driver-registrar
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
        {{- with .Values.csiNodeDriverRegistrar.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      - args:
        - --v=2
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: DRIVER_ROLE
          value: nodeserver
        - name: ENABLE_METRICS
          value: {{ .Values.enableMetrics | quote}}
        - name: METRICS_PORT
          value: {{ .Values.metricsPort | quote}}
        {{- with .Values.csiLinodePlugin.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        image: {{ .Values.csiLinodePlugin.image }}:{{ .Values.csiLinodePlugin.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.csiLinodePlugin.pullPolicy }}
        name: csi-linode-plugin
        securityContext:
          # This container must run as privileged due to the requirement for bidirectional mount propagation
          # See https://github.com/kubernetes/kubernetes/issues/94400
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - SYS_ADMIN
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: {{ .Values.csiLinodePlugin.podsMountDir }}
          mountPropagation: Bidirectional
          name: pods-mount-dir
        - mountPath: /dev
          name: device-dir
        - mountPath: /tmp
          name: tmp
        {{- with .Values.csiLinodePlugin.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.csiLinodePlugin.resources }}
        resources:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccount: csi-node-sa
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: {{ .Values.kubeletPath | default "/var/lib/kubelet" }}/plugins_registry/
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
          path: {{ .Values.kubeletPath | default "/var/lib/kubelet" }}
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: {{ .Values.kubeletPath | default "/var/lib/kubelet" }}/plugins/linodebs.csi.linode.com
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: {{ .Values.csiLinodePlugin.podsMountDir }}
          type: Directory
        name: pods-mount-dir
      - hostPath:
          path: /dev
        name: device-dir
      - hostPath:
          path: /etc/udev
          type: Directory
        name: udev-rules-etc
      - hostPath:
          path: /lib/udev
          type: Directory
        name: udev-rules-lib
      - hostPath:
          path: /run/udev
          type: Directory
        name: udev-socket
      - hostPath:
          path: /sys
          type: Directory
        name: sys
      - hostPath:
          path: /tmp
          type: Directory
        name: tmp
      {{- with .Values.csiLinodePlugin.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
