{{- if .Values.daemonSet.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linode-csi-binding
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linode-csi-role
subjects:
- kind: ServiceAccount
  name: {{ default "csi-node-sa" .Values.daemonSet.serviceAccount.name }}
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
{{- end }}
