// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/filesystem-stats/filesystem_stats.go
//
// Generated by this command:
//
//	mockgen -source=pkg/filesystem-stats/filesystem_stats.go -destination=mocks/mock_filesystemstatter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	unix "golang.org/x/sys/unix"
)

// MockFilesystemStatter is a mock of FilesystemStatter interface.
type MockFilesystemStatter struct {
	ctrl     *gomock.Controller
	recorder *MockFilesystemStatterMockRecorder
	isgomock struct{}
}

// MockFilesystemStatterMockRecorder is the mock recorder for MockFilesystemStatter.
type MockFilesystemStatterMockRecorder struct {
	mock *MockFilesystemStatter
}

// NewMockFilesystemStatter creates a new mock instance.
func NewMockFilesystemStatter(ctrl *gomock.Controller) *MockFilesystemStatter {
	mock := &MockFilesystemStatter{ctrl: ctrl}
	mock.recorder = &MockFilesystemStatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesystemStatter) EXPECT() *MockFilesystemStatterMockRecorder {
	return m.recorder
}

// Statfs mocks base method.
func (m *MockFilesystemStatter) Statfs(path string, stat *unix.Statfs_t) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statfs", path, stat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Statfs indicates an expected call of Statfs.
func (mr *MockFilesystemStatterMockRecorder) Statfs(path, stat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statfs", reflect.TypeOf((*MockFilesystemStatter)(nil).Statfs), path, stat)
}
