// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/mount-manager/safe-mounter.go
//
// Generated by this command:
//
//	mockgen -source=pkg/mount-manager/safe-mounter.go -destination=mocks/mock_mounter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
