{
 "title": "CSI Driver metrics",
 "time": { "from": "2024-10-23T16:04:48.976Z", "to": "2024-10-23T16:37:37.826Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(hpestoragecsi_backend_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(hpestoragecsi_volume_info, pvc_namespace)"
    }
   },
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(hpestoragecsi_volume_info{pvc_namespace=\"$namespace\"}, pvc_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controllerserver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time taken per create volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_controller_create_volume_duration_seconds_count{functionStatus=\"true\"}[5m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per delete volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_controller_delete_volume_duration_seconds_count{functionStatus=\"true\"}[5m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per publish volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_controller_publish_volume_duration_seconds_count{functionStatus=\"true\"}[5m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per unpublish volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_controller_unpublish_volume_duration_seconds_count{functionStatus=\"true\"}[5m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nodeserver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Time taken per stage volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_node_stage_volume_duration_seconds_count{functionStatus=\"true\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per unstage volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_node_unstage_volume_duration_seconds_count{functionStatus=\"true\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per publish volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_node_publish_duration_seconds_count{functionStatus=\"false\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per unpublish volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_node_unpublish_duration_seconds_count{functionStatus=\"true\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per expand volume operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_node_expand_duration_seconds_count{functionStatus=\"true\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sidecar Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Runtime Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(kubelet_runtime_operations_errors_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CSI Sidecar Operations Seconds Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_sidecar_operations_seconds_count[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "round(rate(workqueue_adds_total{name=\"volumes\"}[10m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "round(rate(workqueue_adds_total{name=\"claims\"}[10m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of pods up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 59 },
   "targets": [
    { "expr": "sum(kube_pod_status_ready)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Create Volume",
   "type": "timeseries",
   "description": "Number of create volume requests made",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "round(rate(csi_sidecar_operations_seconds_count{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/CreateVolume\"}[10m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per create volume request",
   "type": "timeseries",
   "description": "Time taken in seconds to create volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_sidecar_operations_seconds_sum{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/CreateVolume\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publish Volume",
   "type": "timeseries",
   "description": "Number of publish volume requests made",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "round (rate(csi_sidecar_operations_seconds_count{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/ControllerPublishVolume\"}[10m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per publish volume request",
   "type": "timeseries",
   "description": "Time taken in seconds to publish volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_sidecar_operations_seconds_sum{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/ControllerPublishVolume\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delete Volume",
   "type": "timeseries",
   "description": "Number of delete volume requests made",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "round (rate(csi_sidecar_operations_seconds_count{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/DeleteVolume\"}[10m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken per delete volume request",
   "type": "timeseries",
   "description": "Time taken in seconds to delete volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_sidecar_operations_seconds_sum{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/DeleteVolume\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unpublish Volume",
   "type": "timeseries",
   "description": "Number of unpublish volume requests made",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "round (rate(csi_sidecar_operations_seconds_count{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/ControllerUnpublishVolume\"}[10m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total time taken to unpublish volume",
   "type": "timeseries",
   "description": "Time taken in seconds to unpublish volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_sidecar_operations_seconds_sum{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/ControllerUnpublishVolume\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Expand Volume",
   "type": "timeseries",
   "description": "Number of extend volume requests made",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "round (rate(csi_sidecar_operations_seconds_count{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/ControllerExpandVolume\"}[10m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total time taken to expand volume",
   "type": "timeseries",
   "description": "Time taken in seconds to expand a volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(csi_sidecar_operations_seconds_sum{driver_name=\"linodebs.csi.linode.com\",grpc_status_code=\"OK\",method_name=\"/csi.v1.Controller/ControllerExpandVolume\"}[10m]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 107 },
   "options": {
    "content": "**Tip:** Click the IOPS line graph and select **Volume Details** for additional volume metrics.            "
   },
   "targets": [
    {}
   ]
  }
 ]
}