apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  ports:
    - port: 80          # The port to expose externally on the NodeBalancer
      targetPort: 3000   # The Grafana target port
      protocol: TCP
      name: http
